//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WXTest.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Getinge_Product
    {
        public int product_id { get; set; }
        public Nullable<int> parent_id { get; set; }
        public Nullable<int> dept_id { get; set; }
        public string product_name { get; set; }
        public string product_mark { get; set; }
        public Nullable<int> product_level { get; set; }
    }
}
