//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WXTest.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class wxtest_dbEntities : DbContext
    {
        public wxtest_dbEntities()
            : base("name=wxtest_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ecmo_User> Ecmo_User { get; set; }
        public virtual DbSet<Ecmo_Enroll> Ecmo_Enroll { get; set; }
        public virtual DbSet<Getinge_Product_Info> Getinge_Product_Info { get; set; }
        public virtual DbSet<Getinge_Dept_Product> Getinge_Dept_Product { get; set; }
        public virtual DbSet<Getinge_Product> Getinge_Product { get; set; }
    }
}
